/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesStudentCardRouteImport } from './routes/exercises/student-card'
import { Route as ExercisesStatusBadgeRouteImport } from './routes/exercises/status-badge'
import { Route as ExercisesAccordionRouteImport } from './routes/exercises/accordion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesStudentCardRoute = ExercisesStudentCardRouteImport.update({
  id: '/exercises/student-card',
  path: '/exercises/student-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesStatusBadgeRoute = ExercisesStatusBadgeRouteImport.update({
  id: '/exercises/status-badge',
  path: '/exercises/status-badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesAccordionRoute = ExercisesAccordionRouteImport.update({
  id: '/exercises/accordion',
  path: '/exercises/accordion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises/accordion'
    | '/exercises/status-badge'
    | '/exercises/student-card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises/accordion'
    | '/exercises/status-badge'
    | '/exercises/student-card'
  id:
    | '__root__'
    | '/'
    | '/exercises/accordion'
    | '/exercises/status-badge'
    | '/exercises/student-card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesAccordionRoute: typeof ExercisesAccordionRoute
  ExercisesStatusBadgeRoute: typeof ExercisesStatusBadgeRoute
  ExercisesStudentCardRoute: typeof ExercisesStudentCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/student-card': {
      id: '/exercises/student-card'
      path: '/exercises/student-card'
      fullPath: '/exercises/student-card'
      preLoaderRoute: typeof ExercisesStudentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/status-badge': {
      id: '/exercises/status-badge'
      path: '/exercises/status-badge'
      fullPath: '/exercises/status-badge'
      preLoaderRoute: typeof ExercisesStatusBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/accordion': {
      id: '/exercises/accordion'
      path: '/exercises/accordion'
      fullPath: '/exercises/accordion'
      preLoaderRoute: typeof ExercisesAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesAccordionRoute: ExercisesAccordionRoute,
  ExercisesStatusBadgeRoute: ExercisesStatusBadgeRoute,
  ExercisesStudentCardRoute: ExercisesStudentCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
