/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesTabsRouteImport } from './routes/exercises/tabs'
import { Route as ExercisesStudentCardRouteImport } from './routes/exercises/student-card'
import { Route as ExercisesStatusBadgeRouteImport } from './routes/exercises/status-badge'
import { Route as ExercisesFilterableListRouteImport } from './routes/exercises/filterable-list'
import { Route as ExercisesClassroomRouteImport } from './routes/exercises/classroom'
import { Route as ExercisesAccordionRouteImport } from './routes/exercises/accordion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesTabsRoute = ExercisesTabsRouteImport.update({
  id: '/exercises/tabs',
  path: '/exercises/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesStudentCardRoute = ExercisesStudentCardRouteImport.update({
  id: '/exercises/student-card',
  path: '/exercises/student-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesStatusBadgeRoute = ExercisesStatusBadgeRouteImport.update({
  id: '/exercises/status-badge',
  path: '/exercises/status-badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesFilterableListRoute = ExercisesFilterableListRouteImport.update({
  id: '/exercises/filterable-list',
  path: '/exercises/filterable-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesClassroomRoute = ExercisesClassroomRouteImport.update({
  id: '/exercises/classroom',
  path: '/exercises/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesAccordionRoute = ExercisesAccordionRouteImport.update({
  id: '/exercises/accordion',
  path: '/exercises/accordion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/classroom': typeof ExercisesClassroomRoute
  '/exercises/filterable-list': typeof ExercisesFilterableListRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
  '/exercises/tabs': typeof ExercisesTabsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/classroom': typeof ExercisesClassroomRoute
  '/exercises/filterable-list': typeof ExercisesFilterableListRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
  '/exercises/tabs': typeof ExercisesTabsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises/accordion': typeof ExercisesAccordionRoute
  '/exercises/classroom': typeof ExercisesClassroomRoute
  '/exercises/filterable-list': typeof ExercisesFilterableListRoute
  '/exercises/status-badge': typeof ExercisesStatusBadgeRoute
  '/exercises/student-card': typeof ExercisesStudentCardRoute
  '/exercises/tabs': typeof ExercisesTabsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises/accordion'
    | '/exercises/classroom'
    | '/exercises/filterable-list'
    | '/exercises/status-badge'
    | '/exercises/student-card'
    | '/exercises/tabs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises/accordion'
    | '/exercises/classroom'
    | '/exercises/filterable-list'
    | '/exercises/status-badge'
    | '/exercises/student-card'
    | '/exercises/tabs'
  id:
    | '__root__'
    | '/'
    | '/exercises/accordion'
    | '/exercises/classroom'
    | '/exercises/filterable-list'
    | '/exercises/status-badge'
    | '/exercises/student-card'
    | '/exercises/tabs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesAccordionRoute: typeof ExercisesAccordionRoute
  ExercisesClassroomRoute: typeof ExercisesClassroomRoute
  ExercisesFilterableListRoute: typeof ExercisesFilterableListRoute
  ExercisesStatusBadgeRoute: typeof ExercisesStatusBadgeRoute
  ExercisesStudentCardRoute: typeof ExercisesStudentCardRoute
  ExercisesTabsRoute: typeof ExercisesTabsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/tabs': {
      id: '/exercises/tabs'
      path: '/exercises/tabs'
      fullPath: '/exercises/tabs'
      preLoaderRoute: typeof ExercisesTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/student-card': {
      id: '/exercises/student-card'
      path: '/exercises/student-card'
      fullPath: '/exercises/student-card'
      preLoaderRoute: typeof ExercisesStudentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/status-badge': {
      id: '/exercises/status-badge'
      path: '/exercises/status-badge'
      fullPath: '/exercises/status-badge'
      preLoaderRoute: typeof ExercisesStatusBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/filterable-list': {
      id: '/exercises/filterable-list'
      path: '/exercises/filterable-list'
      fullPath: '/exercises/filterable-list'
      preLoaderRoute: typeof ExercisesFilterableListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/classroom': {
      id: '/exercises/classroom'
      path: '/exercises/classroom'
      fullPath: '/exercises/classroom'
      preLoaderRoute: typeof ExercisesClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/accordion': {
      id: '/exercises/accordion'
      path: '/exercises/accordion'
      fullPath: '/exercises/accordion'
      preLoaderRoute: typeof ExercisesAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesAccordionRoute: ExercisesAccordionRoute,
  ExercisesClassroomRoute: ExercisesClassroomRoute,
  ExercisesFilterableListRoute: ExercisesFilterableListRoute,
  ExercisesStatusBadgeRoute: ExercisesStatusBadgeRoute,
  ExercisesStudentCardRoute: ExercisesStudentCardRoute,
  ExercisesTabsRoute: ExercisesTabsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
